In [2]:
import pandas as pd
data = pd.read_csv("D:\download\MSN - MSN.csv")
data.head()

  Ticker        Date/Time  Open  High   Low  Close  Volume  Open Interest
0    MSN  12/25/2017 9:15  73.1  73.1  73.1   73.1    4210              0
1    MSN  12/25/2017 9:16  73.0  73.0  73.0   73.0    5000              0
2    MSN  12/25/2017 9:18  73.5  73.5  73.5   73.5     210              0
3    MSN  12/25/2017 9:20  73.2  73.5  73.1   73.1    2050              0
4    MSN  12/25/2017 9:21  73.0  73.0  73.0   73.0    1380              0

In [ ]:
import matplotlib.pyplot as plt

# Biểu đồ dạng nến
plt.figure(figsize=(12, 6))
plt.plot(data['Date/Time'], data['Close'], label='Giá đóng cửa')
plt.xlabel('Thời gian')
plt.ylabel('Giá cổ phiếu')
plt.title('Biểu đồ Giá cổ phiếu theo thời gian')
plt.legend()
plt.show()